# docker-compose.yml
version: "3.8"

services:

    backend:
        container_name: backend
        ports:
            - "8000:8000"
        extra_hosts:
            - "host.docker.internal:host-gateway"